import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { useServerInsertedHTML } from 'next/navigation';
import {CommonLayout} from "@repo/ui/commonLayout";
import {Test} from "./Test";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Test>
          {children}
      </Test>
      </body>
    </html>
  )
}
